language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_install:
  - if [[ ${TRAVIS_PHP_VERSION:0} == "5" ]]; then composer require --dev --no-update phpunit/phpunit ~4; else composer require --dev --no-update phpunit/phpunit fi